/* ----------------------------------------------------------------------------------- */
/* Copyright (C) Simplovation LLC (http://Simplovation.com) 2016. All rights reserved. */
/* Licensing information available at http://webmapsve.codeplex.com                    */
/* ----------------------------------------------------------------------------------- */
/*TileLayerExtender.js*/
Type.registerNamespace("Simplovation.Web.Maps.VE.Extenders");
Simplovation.Web.Maps.VE.Extenders.TileLayerExtender=function(element){Simplovation.Web.Maps.VE.Extenders.TileLayerExtender.initializeBase(this, [element]);this._TileSources=null;this.map=null;};
Simplovation.Web.Maps.VE.Extenders.TileLayerExtender.prototype={initialize:function(){Simplovation.Web.Maps.VE.Extenders.TileLayerExtender.callBaseMethod(this,"initialize");this.map=$find(this.get_element().id);for(var i=0;i<this._TileSources.length;i++){var t=this._TileSources[i];if (t.ID==null){throw new Error.argumentNull("ID","TileSourceSpecification.ID is required.");}if (t.TileSource==null){throw new Error.argumentNull("TileSource","TileSourceSpecification.TileSource is required.");}var ts=new VETileSourceSpecification(t.ID, Simplovation.Web.Maps.VE.Utils.UrlHelper.ToAbsolute(t.TileSource,this.map.get_AppPathRoot()));if(t.Bounds!=null){if(t.Bounds.length!=0){var bounds=new Array();for(var b=0;b<t.Bounds.length;b++){var r=t.Bounds[b];bounds[bounds.length]=new VELatLongRectangle(r.TopLeftLatLong==null?null:new VELatLong(r.TopLeftLatLong.Latitude,r.TopLeftLatLong.Longitude),r.BottomRightLatLong==null?null:new VELatLong(r.BottomRightLatLong.Latitude,r.BottomRightLatLong.Longitude),r.TopRightLatLong==null?null:new VELatLong(r.TopRightLatLong.Latitude,r.TopRightLatLong.Longitude),r.BottomLeftLatLong==null?null:new VELatLong(r.BottomLeftLatLong.Latitude,r.BottomLeftLatLong.Longitude));}ts.Bounds=bounds;}}if(t.MaxZoom!=null){ts.MaxZoom=t.MaxZoom;}if(t.MinZoom!=null){ts.MinZoom=t.MinZoom;}if(t.NumServers!=null){ts.NumServers=t.NumServers;}if(t.Opacity!=null){ts.Opacity=t.Opacity;}if(t.ZIndex!=null){ts.ZIndex=t.ZIndex;}if(t.GetTilePath!=null){ts.GetTilePath=t.GetTilePath;}var v=true;if(t.VisibleOnLoad!=null){v=t.VisibleOnLoad;}this.map.AddTileLayer(ts,v);}},dispose:function(){Simplovation.Web.Maps.VE.Extenders.TileLayerExtender.callBaseMethod(this,"dispose");},get_TileSources:function(){return this._TileSources;},set_TileSources:function(v){this._TileSources=v;this.raisePropertyChanged("TileSources");}};
Simplovation.Web.Maps.VE.Extenders.TileLayerExtender.registerClass("Simplovation.Web.Maps.VE.Extenders.TileLayerExtender",Sys.UI.Behavior);
Sys.Application.notifyScriptLoaded();